### ISSUE TITLE
Explicitly instantiating `batch<>` and/or `batch_bool<>` causes compilation failures

### ISSUE THREAD

**Issue by marzer** [xtensor-stack/xsimd#792]
Hiya,

Have been experimenting with ways to reduce compile times in our work codebase, thought I'd try `extern template`-ing some of the `batch<>` and `batch_bool<>` instances we use so they're only compiled in one TU. Unfortunately both classes fail to compile for a mixed bag of reasons when explicitly instantiated.

Simple repro:

```cpp
#include <xsimd/xsimd.hpp>

namespace xsimd
{
	template class batch<float>;
}

int main()
{
	return 0;
}
```

For the example above, MSVC, GCC and Clang all fail with some version of this:
```
././xsimd/config/../types/../types/xsimd_batch.hpp:698:24: error: no matching function for call to 'mod'
        return *this = kernel::mod<A>(*this, other, A {});
                       ^~~~~~~~~~~~~~
main.cpp:5:17: note: in instantiation of member function 'xsimd::batch<float>::operator%=' requested here
        template class batch<float>;
```

If you change the instantiation to a `batch_bool<>` of your choice, you instead get this on MSVC:
```
xsimd\types\xsimd_batch.hpp(272,1): error C2678: binary '=': no operator found which takes a left-hand
operand of type 'const xsimd::batch_bool<float,xsimd::default_arch>' (or there is no acceptable conversion)
```

Clang and GCC the same issue, but issue a better diagnostic:
```
././xsimd/config/../types/../types/xsimd_batch.hpp:270:89: error: no viable overloaded '='
        batch_bool& operator&=(batch_bool const& other) const noexcept { return (*this) = (*this) & other; }
                                                                                ~~~~~~~ ^ ~~~~~~~~~~~~~~~
main.cpp:5:17: note: in instantiation of member function 'xsimd::batch_bool<float>::operator&=' requested here
        template class batch_bool<float>;
```

I tested the above on SSE2, AVX and AVX2, though the nature of the errors don't appear ISA-related.

Not sure why these issues are only coming up when the templates are explicitly instantiated, might be that there's some internal template dots that otherwise aren't explicitly connected and the compilers are instantiating those parts lazily.

**Comment by serge-sans-paille** [comment]
I can reproduce, let me investigate...

**Comment by serge-sans-paille** [comment]
This should be fixed by #838. Intuitively, explicit instantiation of batch types should have a bad impact on runtime performance, I'd be curious to read your feedback on that aspect.

**Comment by marzer** [comment]
> Intuitively, explicit instantiation of batch types should have a bad impact on runtime performance,

Possibly? I was unable to test on account of the compilation failures. I did set the instantiation TU to have max optimization though, so I suspect the impact would be negligible (or even a net performance gain in debug builds).

**Comment by marzer** [comment]
@serge-sans-paille I'm trying to test this now, and since 63afe75 I can't compile in MSVC (vs 17.4.0 Preview 2.1). Lots of 'ambiguous symbol' errors relating to `has_simd_register`:

```
xsimd_traits.hpp(64,1): error C2872: 'has_simd_register<float,xsimd::avx>': ambiguous symbol
xsimd_traits.hpp(64,1): error C2872:             static_assert(!A::supported() || has_simd_register<T, A>::value,
xsimd_traits.hpp(64,1): error C2872: ^ (compiling source file src\simulation_manager.cpp)
xsimd_traits.hpp(64,46): message : could be 'xsimd::has_simd_register<T,A>'
xsimd_traits.hpp(64,46): message :         with
xsimd_traits.hpp(64,46): message :         [
xsimd_traits.hpp(64,46): message :             T=float,
xsimd_traits.hpp(64,46): message :             A=xsimd::avx
xsimd_traits.hpp(64,46): message :         ]
xsimd_traits.hpp(64,46): message :             static_assert(!A::supported() || has_simd_register<T, A>::value,
xsimd_traits.hpp(64,46): message :                                              ^ (compiling source file src\simulation_manager.cpp)
xsimd_avx_register.hpp(57,9): message : or       'xsimd::types::has_simd_register<float,xsimd::avx>'
xsimd_avx_register.hpp(57,9): message :         XSIMD_DECLARE_SIMD_REGISTER(float, avx, __m256);
xsimd_avx_register.hpp(57,9): message :         ^ (compiling source file src\simulation_manager.cpp)
xsimd_traits.hpp(83): message : see reference to class template instantiation 'xsimd::detail::static_check_supported_config_emitter<T,A>' being compiled
xsimd_traits.hpp(83): message :         with
xsimd_traits.hpp(83): message :         [
xsimd_traits.hpp(83): message :             T=float,
xsimd_traits.hpp(83): message :             A=xsimd::avx
xsimd_traits.hpp(83): message :         ]
xsimd_traits.hpp(83): message :         { (compiling source file src\simulation_manager.cpp)
xsimd_batch.hpp(460): message : see reference to function template instantiation 'void xsimd::detail::static_check_supported_config<T,A>(void)' being compiled
xsimd_batch.hpp(460): message :         with
xsimd_batch.hpp(460): message :         [
xsimd_batch.hpp(460): message :             T=float,
xsimd_batch.hpp(460): message :             A=xsimd::avx
xsimd_batch.hpp(460): message :         ]
xsimd_batch.hpp(460): message :         detail::static_check_supported_config<T, A>(); (compiling source file src\simulation_manager.cpp)
xsimd_batch.hpp(458): message : while compiling class template member function 'xsimd::batch<float,Arch>::batch(T) noexcept'
xsimd_batch.hpp(458): message :         with
xsimd_batch.hpp(458): message :         [
xsimd_batch.hpp(458): message :             Arch=xsimd::avx,
xsimd_batch.hpp(458): message :             T=float
xsimd_batch.hpp(458): message :         ]
xsimd_batch.hpp(458): message :         : types::simd_register<T, A>(kernel::broadcast<A>(val, A {})) (compiling source file src\simulation_manager.cpp)

```
