### ISSUE TITLE
Failed to build with gcc-8.4.0 -std=c++14

### ISSUE THREAD

**Issue by hdu-sdlzx** [xtensor-stack/xsimd#1323]
# Problem

The <version> header is introduced in C++20.

# Build Log

```
$ g++ test.cpp -I./include -std=c++14
In file included from ./include/xsimd/types/../arch/./xsimd_common.hpp:16,
                 from ./include/xsimd/types/../arch/xsimd_isa.hpp:140,
                 from ./include/xsimd/types/xsimd_batch.hpp:520,
                 from ./include/xsimd/xsimd.hpp:77,
                 from test.cpp:1:
./include/xsimd/types/../arch/././common/xsimd_common_bit.hpp:8:10: fatal error: version: No such file or directory
 #include <version>
          ^~~~~~~~~
compilation terminated.
```

**Comment by serge-sans-paille** [comment]
You fixed that one in #1324 🙇
