### PR TITLE
Fix NEON64 bitwidth to 128

### PR DESCRIPTION
**Pull request by guyuqi**
Failed to build on Arm64 (Arm64 gcc (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0).
The data bitwidth of Arm64 Neon extension should be set to 128.
```
/home/yuqi/xsimd/test/test_arch.cpp:53:11: error: ‘batch acc’ has incomplete type
   53 |     batch acc(static_cast<T>(0));
      |           ^~~
/home/yuqi/xsimd/test/test_arch.cpp:54:29: error: incomplete type ‘batch’ {aka ‘xsimd::batch<unsigned int, 16>’} used in nested name specifier
   54 |     const unsigned n = size / batch::size * batch::size;
      |                        ~~~~~^~~~~~~~~~~~~
/home/yuqi/xsimd/test/test_arch.cpp:54:43: error: incomplete type ‘batch’ {aka ‘xsimd::batch<unsigned int, 16>’} used in nested name specifier
   54 |     const unsigned n = size / batch::size * batch::size;
      |                        ~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~
/home/yuqi/xsimd/test/test_arch.cpp:55:35: error: incomplete type ‘batch’ {aka ‘xsimd::batch<unsigned int, 16>’} used in nested name specifier
   55 |     for(unsigned i = 0; i != n; i += batch::size)
      |                                 ~~^~~~~~~~~~~~~~
/home/yuqi/xsimd/test/test_arch.cpp:56:16: error: invalid use of incomplete type ‘using batch = xsimd::arch::batch<unsigned int, xsimd::arch::neon64>’ {aka ‘class xsimd::batch<unsigned int, 16>’}
   56 |         acc += batch(data + i);
```

### CODE REVIEW

**Comment by serge-sans-paille** [comment]
I'm worried this wasn't detected by validation. Let me investigate that.

**Comment by guyuqi** [comment]
> investigate

The error log looks tricky and not relevant to Neon64. 
But when fixing bitwidth to 128, we could successfully build the project and pass the related tests.

**Comment by serge-sans-paille** [comment]
Can you confirm #479 works fine as a fix? It's close to yours, but also adds a CI run.

**Comment by guyuqi** [comment]
> Can you confirm #479 works fine as a fix? It's close to yours, but also adds a CI run.

Of course, I would like to test it later.

**Comment by serge-sans-paille** [comment]
Obsoleted by #479
