### ISSUE TITLE
What are compatible xsimd and xtensor versions ?

### ISSUE THREAD

**Issue by dhk27182** [xtensor-stack/xsimd#569]
Hi,
I'm confused about what are compatible versions of `xsimd` and `xtensor`.

The xtensor README says, xtensor-0.23.10 needs xsimd higher than 7.4.8.

But when I want to compile the xtensor tests from 0.23.10, cmake requires xsimd 7.4.4.

When I compile with xsimd 7.4.4, there are compilation errors - the first one looks like this:
`<MY_PATH_PREFIX>/xtensor-stack/include/xsimd/memory/xsimd_load_store.hpp:392:17: error: no matching function for call to ‘xsimd::batch<int, 16>::store_aligned(bool*&) const’`
           ` 392 |                 src.store_aligned(dst);`

`In file included from <MY_PATH_PREFIX>/xtensor-stack/include/xsimd/types/xsimd_traits.hpp:16,
                 from <MY_PATH_PREFIX>/xtensor-stack/include/xsimd/xsimd.hpp:16,
                 from <MY_PATH_PREFIX>/xtensor/include/xtensor/xtensor_config.hpp:75,
                 from <MY_PATH_PREFIX>/xtensor/include/xtensor/xbuffer_adaptor.hpp:21,
                 from <MY_PATH_PREFIX>/xtensor/include/xtensor/xarray.hpp:19,
                 from <MY_PATH_PREFIX>/xtensor/test/test_xarray.cpp:11:`

So which versions are recommended to be used together ?

Thanks

**Comment by SylvainCorlay** [comment]
The cmake may need to be updated.

**Comment by dhk27182** [comment]
Simply changing the required xsimd-version in xtensor's (0.23.10) CMakeList.txt has not been successful.

I was not able to compile the tests with `XTENSOR_USE_XSIMD=ON` with xsimd 7.4.9, neither with 7.5.0 nor 7.6.0.
With `XTENSOR_USE_XSIMD=OFF`, its OK.

**Comment by JohanMabille** [comment]
It looks like you're not looking at the right file (or your install of older versions did not erase 8.0.0). The versions are correctly defined in `xsimd/config/xsimd_config.hpp`:

[config 7.4.9](https://github.com/xtensor-stack/xsimd/blob/7.4.9/include/xsimd/config/xsimd_config.hpp#L16)
[config 7.5.0](https://github.com/xtensor-stack/xsimd/blob/7.5.0/include/xsimd/config/xsimd_config.hpp#L16)
[config 7.6.0](https://github.com/xtensor-stack/xsimd/blob/7.6.0/include/xsimd/config/xsimd_config.hpp)

**Comment by dhk27182** [comment]
Ok, thank you, I will try to do a really clean install.

**Comment by dhk27182** [comment]
Well, after a clean install the tests also compiled with `XTENSOR_USE_XSIMD=ON`. It seems that I made a mistake with `git`when trying to checkout the tagged release.

So I will close the issue now. And thanks for the hint  to the problem !
